"use client";

import { ArrowLeft, BarChart3, CloudSun, Download, History, LoaderCircle, LogOut, PlugZap, RefreshCw, Table2, Upload } from "lucide-react";
import { Area, CartesianGrid, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useCallback, useEffect, useMemo, useState } from "react";

type RangeKey = "24h" | "7d" | "30d" | "1y";
type Point = { time: number; value: number };
type Series = { unit: string; points: Point[] };
type WeatherResponse = { history: Record<string, Series> };
type GenerationResponse = { connected: boolean; message?: string; history?: { generation: Series; consumption: Series; gridImport: Series; gridExport: Series } };
type ViewMode = "chart" | "table";

const RANGES: { value: RangeKey; label: string }[] = [{ value: "24h", label: "Dia" }, { value: "7d", label: "Semana" }, { value: "30d", label: "Mês" }, { value: "1y", label: "Ano" }];
const COLORS = { generation: "#f6c64e", radiation: "#f48c2c", import: "#bc8cff", export: "#56d7a5" };
const zone = { timeZone: "America/Sao_Paulo" };
const rangeLabel = (range: RangeKey) => RANGES.find((item) => item.value === range)?.label ?? range;
const number = (value: number | undefined, unit: string, digits = 1) => typeof value === "number" && Number.isFinite(value) ? `${value.toLocaleString("pt-BR", { maximumFractionDigits: digits })} ${unit}` : "—";
const total = (points?: Point[]) => points?.reduce((sum, point) => sum + point.value, 0) ?? 0;
const dateKey = (time: number, range: RangeKey) => new Intl.DateTimeFormat("en-CA", { ...zone, year: "numeric", month: "2-digit", ...(range === "1y" ? {} : { day: "2-digit" }) }).format(new Date(time));
const startOfBucket = (key: string) => Date.parse(`${key}${key.length === 7 ? "-01" : ""}T00:00:00-03:00`);

function axisTick({ x = 0, y = 0, payload, range }: { x?: number; y?: number; payload?: { value: number }; range: RangeKey }) {
  const date = new Date(Number(payload?.value));
  if (!Number.isFinite(date.getTime())) return null;
  const label = range === "24h" ? date.toLocaleTimeString("pt-BR", { ...zone, hour: "2-digit", minute: "2-digit" }) : range === "1y" ? date.toLocaleDateString("pt-BR", { ...zone, month: "short" }) : date.toLocaleDateString("pt-BR", { ...zone, day: "2-digit", month: "2-digit" });
  return <text x={x} y={y} textAnchor="middle" fill="#9eb0bb" fontSize={11}>{label}</text>;
}
function radiationBuckets(points: Point[] | undefined) { return points?.map((point) => ({ time: point.time, radiation: point.value })) ?? []; }

export default function GenerationDashboard({ userName }: { userName: string }) {
  const [range, setRange] = useState<RangeKey>("7d");
  const [view, setView] = useState<ViewMode>("chart");
  const [weather, setWeather] = useState<WeatherResponse | null>(null);
  const [generation, setGeneration] = useState<GenerationResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (quiet = false) => { if (quiet) setRefreshing(true); else setLoading(true); try { const [weatherResult, generationResult] = await Promise.all([fetch(`/api/weather?range=${range}&view=solar`), fetch(`/api/generation?range=${range}`)]); if (weatherResult.ok) setWeather(await weatherResult.json() as WeatherResponse); const generationBody = await generationResult.json() as GenerationResponse; setGeneration(generationResult.ok ? generationBody : { connected: false, message: generationBody.message ?? "Não foi possível carregar os dados da APsystems." }); } finally { setLoading(false); setRefreshing(false); } }, [range]);
  useEffect(() => { load(); }, [load]);
  const rows = useMemo(() => { const map = new Map<number, Record<string, number>>(); const add = (key: string, points: Point[] | undefined) => points?.forEach((point) => { const row = map.get(point.time) ?? { time: point.time }; row[key] = point.value; map.set(point.time, row); }); radiationBuckets(weather?.history.solar?.points).forEach((point) => { const row = map.get(point.time) ?? { time: point.time }; row.radiation = point.radiation; map.set(point.time, row); }); add("generation", generation?.history?.generation.points); add("consumption", generation?.history?.consumption.points); add("gridImport", generation?.history?.gridImport.points); add("gridExport", generation?.history?.gridExport.points); return [...map.values()].sort((a, b) => a.time - b.time); }, [weather, generation]);
  const energy = generation?.history;
  const averageRadiation = rows.filter((row) => row.radiation !== undefined).reduce((sum, row, _, array) => sum + (row.radiation ?? 0) / array.length, 0);
  const ChartHeader = ({ eyebrow, title, detail }: { eyebrow: string; title: string; detail: string }) => <header><div><span>{eyebrow}</span><h2>{title}</h2></div><p>{detail}</p></header>;
  const chartData = rows as Array<{ time: number; radiation?: number; generation?: number; consumption?: number; gridImport?: number; gridExport?: number }>;
  return <main className="generation-shell"><header className="generation-topbar"><a href="/#map" className="back-link"><ArrowLeft size={17} />Estação Bauru Sul</a><div className="generation-user"><span>Área privada · {userName}</span><a href="/signout-with-chatgpt?return_to=%2F" aria-label="Sair da área privada"><LogOut size={16} /></a></div></header>
    <section className="generation-hero"><div><span>APSYSTEMS + ESTAÇÃO BAURU SUL</span><h1>Energia Solar e Fluxo da Rede</h1><p>Produção solar, radiação e energia trocada com a rede no mesmo período.</p></div><button className="generation-refresh" onClick={() => load(true)} disabled={refreshing}>{refreshing ? <LoaderCircle className="spin" size={17} /> : <RefreshCw size={17} />}Atualizar dados</button></section>
    <section className="generation-toolbar" aria-label="Período da análise">{RANGES.map((item) => <button key={item.value} className={range === item.value ? "active" : ""} onClick={() => setRange(item.value)}>{item.label}</button>)}</section>
    <section className="generation-view-toggle" aria-label="Forma de visualização"><button className={view === "chart" ? "active" : ""} onClick={() => setView("chart")}><BarChart3 size={16} />Gráficos</button><button className={view === "table" ? "active" : ""} onClick={() => setView("table")}><Table2 size={16} />Valores numéricos</button></section>
    {generation?.connected === false && <div className="generation-note"><PlugZap size={18} /><div><strong>Conexão APsystems indisponível</strong><span>{generation.message ?? "Não foi possível consultar os dados de energia."}</span></div></div>}
    <section className="generation-metrics"><article><History /><span>Geração solar</span><strong>{number(energy?.generation.points.at(-1)?.value, "W")}</strong><small>Última leitura APsystems</small></article><article><CloudSun /><span>Radiação atual</span><strong>{number(rows.at(-1)?.radiation, "W/m²", 0)}</strong><small>Curva completa da estação</small></article><article><Download /><span>Consumo</span><strong>{number(energy?.consumption.points.at(-1)?.value, "W")}</strong><small>Última leitura APsystems</small></article><article><Upload /><span>Fluxo da rede</span><strong>{number(energy?.gridImport.points.at(-1)?.value, "W")}</strong><small>Importação atual</small></article></section>
    {view === "table" ? <section className="generation-card"><ChartHeader eyebrow="LEITURAS POR INTERVALO" title="Valores por período" detail={`${rangeLabel(range)} · horário de Bauru`} /><div className="generation-table-wrap"><table className="generation-table"><thead><tr><th>Horário</th><th>Radiação</th><th>Produção</th><th>Consumo</th><th>Importação</th><th>Exportação</th></tr></thead><tbody>{chartData.map((row) => <tr key={row.time}><td>{new Date(row.time).toLocaleString("pt-BR", { ...zone, day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" })}</td><td>{number(row.radiation, "W/m²", 0)}</td><td>{number(row.generation, "W")}</td><td>{number(row.consumption, "W")}</td><td>{number(row.gridImport, "W")}</td><td>{number(row.gridExport, "W")}</td></tr>)}</tbody></table></div></section> : <>
      <section className="generation-card"><ChartHeader eyebrow="DESEMPENHO SOLAR" title="Produção x radiação" detail={`${rangeLabel(range)} · potência em W`} /><div className="generation-chart">{loading ? <div className="generation-loading"><LoaderCircle className="spin" />Carregando dados…</div> : <ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData} margin={{ top: 18, right: 16, left: 0, bottom: 0 }}><CartesianGrid stroke="rgba(158,194,209,.12)" vertical={false} /><XAxis dataKey="time" tick={(props) => axisTick({ ...props, range })} minTickGap={36} tickLine={false} axisLine={{ stroke: "#527080" }} /><YAxis yAxisId="energy" tick={{ fill: "#9eb0bb", fontSize: 11 }} tickLine={false} axisLine={false} width={44} /><YAxis yAxisId="radiation" orientation="right" tick={{ fill: "#9eb0bb", fontSize: 11 }} tickLine={false} axisLine={false} width={52} /><Tooltip contentStyle={{ background: "#0a1a24", border: "1px solid #284655", borderRadius: 6 }} labelFormatter={(time) => new Date(Number(time)).toLocaleString("pt-BR", zone)} /><Legend wrapperStyle={{ paddingTop: 12, fontSize: 12 }} /><Area yAxisId="radiation" type="linear" dataKey="radiation" name="Radiação (W/m²)" stroke={COLORS.radiation} fill={COLORS.radiation} fillOpacity={.14} strokeWidth={1.6} connectNulls /><Line yAxisId="energy" type="linear" dataKey="generation" name="Produção (W)" stroke={COLORS.generation} strokeWidth={2.4} dot={false} connectNulls /></ComposedChart></ResponsiveContainer>}</div></section>
      <section className="generation-card generation-card-secondary"><ChartHeader eyebrow="CONSUMO E REDE" title="Consumo, importação x exportação" detail={`${rangeLabel(range)} · potência em W`} /><div className="generation-chart">{loading ? <div className="generation-loading"><LoaderCircle className="spin" />Carregando dados…</div> : <ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData} margin={{ top: 18, right: 16, left: 0, bottom: 0 }}><CartesianGrid stroke="rgba(158,194,209,.12)" vertical={false} /><XAxis dataKey="time" tick={(props) => axisTick({ ...props, range })} minTickGap={36} tickLine={false} axisLine={{ stroke: "#527080" }} /><YAxis tick={{ fill: "#9eb0bb", fontSize: 11 }} tickLine={false} axisLine={false} width={44} /><Tooltip contentStyle={{ background: "#0a1a24", border: "1px solid #284655", borderRadius: 6 }} labelFormatter={(time) => new Date(Number(time)).toLocaleString("pt-BR", zone)} /><Legend wrapperStyle={{ paddingTop: 12, fontSize: 12 }} /><Area type="linear" dataKey="consumption" name="Consumo (W)" stroke="#60d2ef" fill="#60d2ef" fillOpacity={.1} strokeWidth={2.2} connectNulls /><Line type="linear" dataKey="gridImport" name="Importação (W)" stroke={COLORS.import} strokeWidth={2.2} dot={false} connectNulls /><Line type="linear" dataKey="gridExport" name="Exportação (W)" stroke={COLORS.export} strokeWidth={2.4} dot={false} connectNulls /></ComposedChart></ResponsiveContainer>}</div></section>
    </>}</main>;
}
